### ISSUE TITLE
addchat

### ISSUE THREAD

**Issue by HeyLashi** [DoellBarr/solidmusic#20]
Hi
Has a problem
I do not want the robot to be added automatically now
And the addchat command does not work either

**Comment by levina-lab** [comment]
> Hi
> Has a problem
> I do not want the robot to be added automatically now
> And the addchat command does not work either

@HeyLashi what you mean of "__You didn't want the robot added automatically ?, Can you explain it ?__"

**Comment by HeyLashi** [comment]
This means that now I do not want users to be able to add the robot automatically.
Sudo allows a group to use a robot

**Comment by DoellBarr** [comment]
> This means that now I do not want users to be able to add the robot automatically. Sudo allows a group to use a robot

@HeyLashi I can't make that feature, sorry
