### ISSUE TITLE
VPS commands are not right!

### ISSUE THREAD

**Issue by ChankitSaini** [DoellBarr/solidmusic#56]
Just try it on your own to know better!

**VPS:**
 Debian 11 (Gen 2)

**Comment by DoellBarr** [comment]
Give me some reproducible codes

**Comment by ChankitSaini** [comment]
> Give me some reproducible codes

When I tried to run on a fresh Debian 11 (Gen 2) VM,  this struck at installation of pip packages because VPS deployment guide is lacking the command to upgrade pip to latest version by which installation of new pip packages is blocked.

**Comment by DoellBarr** [comment]
@ChankitSaini I never told about &quot;you must to upgrade the pip version&quot;, so that&#x27;s not the problem

**Comment by ChankitSaini** [comment]
> @ChankitSaini I never told about "you must to upgrade the pip version", so that's not the problem

Okay.
